### ISSUE TITLE
Change “Excel” to “XLS” in 3* definition

### ISSUE THREAD

**Issue by andylolz** [mhausenblas/5stardata.info#32]
The 3* definition says:

> make it available in a non-proprietary open format (e.g., CSV instead of Excel)

However, while XLS is a proprietary format, XLSX isn’t. So the example here is ambiguous. It might be better to change “Excel” to “XLS”.

It looks like [the document that this text is lifted from](https://www.w3.org/DesignIssues/LinkedData.html) predates the introduction of XLSX to Excel. So while it may have been correct then, it’s not correct now.

**Comment by akuckartz** [comment]
Those OOXML specifications created by Microsoft are not really open. See http://joinup.ec.europa.eu/document/complex-singularity-versus-openness

**Comment by andylolz** [comment]
Interesting – thanks for this, @akuckartz! I’ll have a read.

**Comment by andylolz** [comment]
Closing this, because I think @akuckartz is quite right. Thanks!
