### ISSUE TITLE
Serve the website over HTTPS

### ISSUE THREAD

**Issue by wouterbeek** [mhausenblas/5stardata.info#38]
Currently the website is served over HTTP (http://5stardata.info/en/).  Since non-SSL sites are becoming increasingly more difficult to visit in modern browsers, please consider serving a version over HTTPS as well.

**Comment by mhausenblas** [comment]
Yup, thanks for the reminder, I've indeed looked into that recently. Moved domain to Namecheap recently and we should be all set now.

**Comment by mhausenblas** [comment]
Should work now
