### ISSUE TITLE
Fix CSV representation

### ISSUE THREAD

**Issue by mhausenblas** [mhausenblas/5stardata.info#7]
As reported by Michael G., the current example for 3star data (the [CSV document](http://5stardata.info/gtd-3.csv)) does not seem to follow [RFC4180](http://tools.ietf.org/html/rfc4180) and he's kindly provided a patch for it:

	"Day","Lowest Temperature (C)"
	"Saturday, 13 November 2010",2
	"Sunday, 14 November 2010",4
	"Monday, 15 November 2010",7

**Comment by jgkim** [comment]
Fixed with https://github.com/mhausenblas/5stardata.info/commit/aab18d2fc39b6b87d442ec8997027b1256e85f3f.
